### ISSUE TITLE
Request: readme

### ISSUE THREAD

**Issue by bwoodruff** [karlg100/homebridge-frigidaire#1]
Hi Brian,

First: Thank you for taking the time to create this.

Second: Would you please consider writing a readme for it? I have two Frigidaire Wi-Fi enabled AC units that I'd like to control via HomeKit / Siri, but I'm just getting into learning about HomeBridge, and am not sure what values I need to modify in the provided files to get a working installation for my setup.

Thanks!

**Comment by andrewtelliott** [comment]
I would also love a readme here.  I'm excited to get my AC on my HB set up.  The (terrible) Frigidaire app is in Cordova, so it seems like a lot of the JS is already available.

I'm wondering if this is such an empty repo because the 2nd half is the (c) js from the app...

**Comment by bwoodruff** [comment]
I spoke with the author, and unfortunately the project is incomplete (so a readme wouldn't really help setting up). He also mentioned he no longer uses the Frigidaire units as he was getting central air installed.

Would love to see someone flesh this the rest of the way out, and would be happy to help test.

**Comment by andrewtelliott** [comment]
That's too bad.  I'll dig in if I can.  I'm pretty interested in HB/HomeKit integrations, as proper HomeKit has SO MANY hubs to deal with.

I'll try to come back here and drop off anything I figure out.  I haven't written any HomeBridge plugins, so it'll be a little bit of learning, which means it won't be very soon :).

**Comment by ShermanThruGA** [comment]
You guys make any progress with it yet?

**Comment by karlg100** [comment]
current version now works.
