### ISSUE TITLE
Expose Fan Speed as Fan Device Type

### ISSUE THREAD

**Issue by dippnerd** [karlg100/homebridge-frigidaire#10]
Would it be possible to expose the Fan Speed controls as a separate Fan device? I see there is some code already handling fan speed, but it doesn't appear user-controllable for the AC settings. A separate fan device may be one remedy for that, unless HomeKit has a way to control it from the Thermostat service too?

**Comment by dippnerd** [comment]
I didn't realize it does expose fan speed in third-party HomeKit apps, just not the native one, so anyone reading this for the future, check any of the alternatives, I specifically used the Home 3 app by Matthias Hochgatterer, but other third party apps probably support it too. Just search "HomeKit" in the app store and try one.

**Comment by tthoma24** [comment]
I believe this may actually be due to the fact that this is defining a Thermostat service, rather than a Heater Cooler service. It appears that the rotation speed characteristic is only supported when using Heater Cooler as the service type, not Thermostat. See section 8.18 and 8.42 of the HAP Spec. 

@karlg100 any reason not to switch over to using the Heater Cooler service type?

**Comment by jakemauer** [comment]
I'd also love to see fan speed exposed in the native Homekit apps. I'm going to fork this repo and see if I can naively switch the service type to heater/cooler to get it to work. Also @karlg100 you put in code for fan control, did it ever show up or work for you in Apple's Homekit apps? 

BTW, Thanks for all your work on this @karlg100. I appreciate it.

**Comment by enz1ey** [comment]
> I'd also love to see fan speed exposed in the native Homekit apps. I'm going to fork this repo and see if I can naively switch the service type to heater/cooler to get it to work. Also @karlg100 you put in code for fan control, did it ever show up or work for you in Apple's Homekit apps?
> 
> BTW, Thanks for all your work on this @karlg100. I appreciate it.

Any progress on your fork? I'd love to be able to control fan speed and switch between cool/eco with automations.

**Comment by karlg100** [comment]
FYI - fan speed can be controlled, but you can’t do so with the native Home app.  Use the Eve app, including setting up automation rules to automatically adjust the fan speed.

![416D5014-CE0F-423E-B0E6-DC0DDDF0A67E](https://user-images.githubusercontent.com/3743991/83508623-2c185d80-a498-11ea-9641-0c77ff2bb957.jpeg)
