### ISSUE TITLE
no response in home.app

### ISSUE THREAD

**Issue by mentaluproar** [karlg100/homebridge-frigidaire#16]
Homebridge sees the air conditioners and adds them to home, but their status always says "no response."

**Comment by amaisano** [comment]
Same. Either v 1.0.4 or 1.0.5 ruined homebridge for me -- all platforms stall out. Reverting back to 1.0.3 which works great: `sudo npm -g i homebridge-frigidaire@1.0.3`

**Comment by mentaluproar** [comment]
I have some debug for you.

> 
> [7/17/2019, 10:14:33 PM] Homebridge is running on port 51826.
> [7/17/2019, 10:14:35 PM] [Config] Console v4.5.1 is listening on :: port 4200
>   frigidaire getting units for 79607 +10s
>   frigidaire getValue() +1ms
>   frigidaire applianceId 79607 attribute 7005 has the value 1 +2ms
>   homebridge-frigidaire getTemperatureDisplayUnits:  1 +4ms
>   homebridge-frigidaire getCurrentHeatingCoolingState:  undefined +1ms
>   frigidaire getting cooling state for 79607 +1ms
>   frigidaire getValue() +1ms
>   frigidaire applianceId 79607 attribute 7011 has the value 0 +1ms
>   homebridge-frigidaire getCurrentHeatingCoolingState:  0 +2ms
>   frigidaire getting mode for 79607 +2ms
>   frigidaire getValue() +1ms
>   frigidaire applianceId 79607 attribute 7002 has the value 1 +0ms
>   homebridge-frigidaire getTargetHeatingCoolingState:  2 +3ms
>   frigidaire getting room temp for 79607 +2ms
>   frigidaire getValue() +1ms
>   frigidaire applianceId 79607 attribute 7004 has the value 760 +0ms
>   homebridge-frigidaire getCurrentTemperature: 76 -> 24.444444444444443 +2ms
>   frigidaire getting temp for 79607 +4ms
>   frigidaire getValue() +0ms
>   frigidaire applianceId 79607 attribute 7003 has the value 740 +1ms
>   homebridge-frigidaire getTargetTemperature: 74 -> 23.333333333333332 +1ms
>   frigidaire getting fan mode for 79607 +3ms
>   frigidaire getValue() +0ms
>   frigidaire applianceId 79607 attribute 7006 has the value 7 +1ms
>   homebridge-frigidaire current fan mode is 7 +1ms
>   homebridge-frigidaire getFanSpeed:  100 +1ms
>   frigidaire getting units for 80027 +4ms
>   frigidaire getValue() +1ms
>   frigidaire applianceId 80027 attribute 7005 has the value 1 +0ms
>   homebridge-frigidaire getTemperatureDisplayUnits:  1 +2ms
>   homebridge-frigidaire getCurrentHeatingCoolingState:  undefined +0ms
>   frigidaire getting cooling state for 80027 +1ms
>   frigidaire getValue() +0ms
>   frigidaire applianceId 80027 attribute 7011 has the value 0 +0ms
>   homebridge-frigidaire getCurrentHeatingCoolingState:  0 +1ms
>   frigidaire getting mode for 80027 +0ms
>   frigidaire getValue() +1ms
>   frigidaire applianceId 80027 attribute 7002 has the value 1 +0ms
>   homebridge-frigidaire getTargetHeatingCoolingState:  2 +1ms
>   frigidaire getting room temp for 80027 +1ms
>   frigidaire getValue() +0ms
>   frigidaire applianceId 80027 attribute 7004 has the value 760 +1ms
>   homebridge-frigidaire getCurrentTemperature: 76 -> 24.444444444444443 +0ms
>   frigidaire getting temp for 80027 +4ms
>   frigidaire getValue() +1ms
>   frigidaire applianceId 80027 attribute 7003 has the value 740 +0ms
>   homebridge-frigidaire getTargetTemperature: 74 -> 23.333333333333332 +1ms
>   frigidaire getting fan mode for 80027 +1ms
>   frigidaire getValue() +1ms
>   frigidaire applianceId 80027 attribute 7006 has the value 7 +1ms
>   homebridge-frigidaire current fan mode is 7 +1ms
>   homebridge-frigidaire getFanSpeed:  100 +0ms
>   frigidaire getTelem() +73ms
>   frigidaire  +2ms
>   frigidaire  +1ms
>   frigidaire get() +1ms
>   frigidaire  +1ms
>   frigidaire attempts: 0 +0ms
>   frigidaire getTelem() +257ms
>   frigidaire  +1ms
>   frigidaire  +0ms
>   frigidaire get() +1ms
>   frigidaire  +0ms
>   frigidaire attempts: 0 +0ms
>   frigidaire getting units for 79607 +10s
>   frigidaire getValue() +1ms
>   frigidaire applianceId 79607 attribute 7005 has the value 1 +0ms
>   homebridge-frigidaire getTemperatureDisplayUnits:  1 +1ms
>   homebridge-frigidaire getCurrentHeatingCoolingState:  0 +0ms
>   frigidaire getting cooling state for 79607 +0ms
>   frigidaire getValue() +1ms
>   frigidaire applianceId 79607 attribute 7011 has the value 0 +0ms
>   homebridge-frigidaire getCurrentHeatingCoolingState:  0 +0ms
>   frigidaire getting mode for 79607 +1ms
>   frigidaire getValue() +0ms
>   frigidaire applianceId 79607 attribute 7002 has the value 1 +0ms
>   homebridge-frigidaire getTargetHeatingCoolingState:  2 +1ms
>   frigidaire getting room temp for 79607 +0ms
>   frigidaire getValue() +0ms
>   frigidaire applianceId 79607 attribute 7004 has the value 760 +1ms
>   homebridge-frigidaire getCurrentTemperature: 76 -> 24.444444444444443 +0ms
>   frigidaire getting temp for 79607 +1ms
>   frigidaire getValue() +1ms
>   frigidaire applianceId 79607 attribute 7003 has the value 740 +0ms
>   homebridge-frigidaire getTargetTemperature: 74 -> 23.333333333333332 +1ms
>   frigidaire getting fan mode for 79607 +2ms
>   frigidaire getValue() +0ms
>   frigidaire applianceId 79607 attribute 7006 has the value 7 +1ms
>   homebridge-frigidaire current fan mode is 7 +0ms
>   homebridge-frigidaire getFanSpeed:  100 +0ms
>   frigidaire getting units for 80027 +30ms
>   frigidaire getValue() +0ms
>   frigidaire applianceId 80027 attribute 7005 has the value 1 +1ms
>   homebridge-frigidaire getTemperatureDisplayUnits:  1 +0ms
>   homebridge-frigidaire getCurrentHeatingCoolingState:  0 +1ms
>   frigidaire getting cooling state for 80027 +0ms
>   frigidaire getValue() +0ms
>   frigidaire applianceId 80027 attribute 7011 has the value 0 +1ms
>   homebridge-frigidaire getCurrentHeatingCoolingState:  0 +0ms
>   frigidaire getting mode for 80027 +0ms
>   frigidaire getValue() +1ms
>   frigidaire applianceId 80027 attribute 7002 has the value 1 +0ms
>   homebridge-frigidaire getTargetHeatingCoolingState:  2 +0ms
>   frigidaire getting room temp for 80027 +1ms
>   frigidaire getValue() +0ms
>   frigidaire applianceId 80027 attribute 7004 has the value 760 +0ms
>   homebridge-frigidaire getCurrentTemperature: 76 -> 24.444444444444443 +0ms
>   frigidaire getting temp for 80027 +1ms
>   frigidaire getValue() +0ms
>   frigidaire applianceId 80027 attribute 7003 has the value 740 +1ms
>   homebridge-frigidaire getTargetTemperature: 74 -> 23.333333333333332 +0ms
>   frigidaire getting fan mode for 80027 +1ms
>   frigidaire getValue() +0ms
>   frigidaire applianceId 80027 attribute 7006 has the value 7 +0ms
>   homebridge-frigidaire current fan mode is 7 +0ms
>   homebridge-frigidaire getFanSpeed:  100 +0ms
>   frigidaire getTelem() +219ms
>   frigidaire  +0ms
>   frigidaire  +1ms
>   frigidaire get() +0ms
>   frigidaire  +0ms
>   frigidaire attempts: 0 +1ms
>   frigidaire getTelem() +520ms
>   frigidaire  +0ms
>   frigidaire  +1ms
>   frigidaire get() +0ms
>   frigidaire  +0ms
>   frigidaire attempts: 0 +0ms
>   frigidaire getting units for 79607 +9s
>   frigidaire getValue() +1ms
>   frigidaire applianceId 79607 attribute 7005 has the value 1 +1ms
>   homebridge-frigidaire getTemperatureDisplayUnits:  1 +1ms
>   homebridge-frigidaire getCurrentHeatingCoolingState:  0 +0ms
>   frigidaire getting cooling state for 79607 +7ms
>   frigidaire getValue() +0ms
>   frigidaire applianceId 79607 attribute 7011 has the value 0 +1ms
>   homebridge-frigidaire getCurrentHeatingCoolingState:  0 +1ms
>   frigidaire getting mode for 79607 +0ms
>   frigidaire getValue() +0ms
>   frigidaire applianceId 79607 attribute 7002 has the value 1 +1ms
>   homebridge-frigidaire getTargetHeatingCoolingState:  2 +0ms
>   frigidaire getting room temp for 79607 +1ms
>   frigidaire getValue() +0ms
>   frigidaire applianceId 79607 attribute 7004 has the value 760 +1ms
>   homebridge-frigidaire getCurrentTemperature: 76 -> 24.444444444444443 +0ms
>   frigidaire getting temp for 79607 +1ms
>   frigidaire getValue() +0ms
>   frigidaire applianceId 79607 attribute 7003 has the value 740 +1ms
>   homebridge-frigidaire getTargetTemperature: 74 -> 23.333333333333332 +0ms
>   frigidaire getting fan mode for 79607 +1ms
>   frigidaire getValue() +0ms
>   frigidaire applianceId 79607 attribute 7006 has the value 7 +1ms
>   homebridge-frigidaire current fan mode is 7 +0ms
>   homebridge-frigidaire getFanSpeed:  100 +1ms
>   frigidaire getting units for 80027 +23ms
>   frigidaire getValue() +0ms
>   frigidaire applianceId 80027 attribute 7005 has the value 1 +1ms
>   homebridge-frigidaire getTemperatureDisplayUnits:  1 +0ms
>   homebridge-frigidaire getCurrentHeatingCoolingState:  0 +1ms
>   frigidaire getting cooling state for 80027 +0ms
>   frigidaire getValue() +0ms
>   frigidaire applianceId 80027 attribute 7011 has the value 0 +0ms
>   homebridge-frigidaire getCurrentHeatingCoolingState:  0 +1ms
>   frigidaire getting mode for 80027 +0ms
>   frigidaire getValue() +0ms
>   frigidaire applianceId 80027 attribute 7002 has the value 1 +1ms
>   homebridge-frigidaire getTargetHeatingCoolingState:  2 +0ms
>   frigidaire getting room temp for 80027 +0ms
>   frigidaire getValue() +1ms
>   frigidaire applianceId 80027 attribute 7004 has the value 760 +0ms
>   homebridge-frigidaire getCurrentTemperature: 76 -> 24.444444444444443 +0ms
>   frigidaire getting temp for 80027 +1ms
>   frigidaire getValue() +0ms
>   frigidaire applianceId 80027 attribute 7003 has the value 740 +0ms
>   homebridge-frigidaire getTargetTemperature: 74 -> 23.333333333333332 +4ms
>   frigidaire getting fan mode for 80027 +1ms
>   frigidaire getValue() +1ms
>   frigidaire applianceId 80027 attribute 7006 has the value 7 +0ms
>   homebridge-frigidaire current fan mode is 7 +1ms
>   homebridge-frigidaire getFanSpeed:  100 +0ms
>   frigidaire getTelem() +348ms
>   frigidaire  +1ms
>   frigidaire  +0ms
>   frigidaire get() +0ms
>   frigidaire  +1ms
>   frigidaire attempts: 0 +0ms
>   frigidaire getTelem() +779ms
>   frigidaire  +1ms
>   frigidaire  +0ms
>   frigidaire get() +1ms
>   frigidaire  +0ms
>   frigidaire attempts: 0 +0ms
> ^C[7/17/2019, 10:15:05 PM] Got SIGINT, shutting down Homebridge...
> [7/17/2019, 10:15:05 PM] [Harmony Hub] INFO - shutdown

**Comment by purplecones** [comment]
Same here. Reverting back to v1.0.3.

**Comment by karlg100** [comment]
Drat.  Will take a look.  I have limited availability if someone wants to take a look.  I think it may be due to the callbacks.  Was having issues where a callback was being called more than once and attempted to prevent that, but apparently broke other stuff.

**Comment by mentaluproar** [comment]
It's strange.  It looks like its getting a response and regularly querying for new data, but it isn't passing it on to home bridge.

**Comment by karlg100** [comment]
found the issue. we were missing a callback() in one of the get functions.  still early testing, but so far much more stable.

also something interesting to note - I had originally done this update so that homeKit will update from the Frigidaire telemetry.  as it turns out, it appears they have a bug in their system.  Telemetry is no longer updating like it used too!  old values are cached for some random period of time in their data stream. (both local button pushes and API updates don't reflect in the telemetry)

I've disabled all but the temperature updates in this mode so HomeKit will just use whatever value you last pushed, except for periodically pulling the room temperature and updating HomeKit.

the workaround is to extend the Frigidaire module to keep track of API updates and update the telemetry cache.  then when checking telemetry, only update objects if they have been stamped as newer.

**Comment by mentaluproar** [comment]
Yay!  Thank you for working on this. It sounds like this fix means less traffic too, which is always a plus.

**Comment by karlg100** [comment]
may not cut down on that much traffic, but hopefully will be more responsive to updates and events.
