### ISSUE TITLE
Frigidaire Mode Names

### ISSUE THREAD

**Issue by ci1025** [karlg100/homebridge-frigidaire#20]
I may have an older model (FGRC0844S1) but while the plugin is fully compatible, the mode names on the plugin do not match up to those on the unit itself. For instance: Auto Mode on the plugin = Eco Mode on my AC unit and Heat Mode on the plugin = Fan mode on my AC unit. Can an option be added to customize these modes for different models?

**Comment by karlg100** [comment]
Unfortunately, no.  The HAP modes are very rigid for an AC Thermostat. "Heat" can't be changed to "Fan" for example.  I remember back to working this out, and went with what made the most sense.

the only alternative was to break everything out into separate devices.  But would have required a lot more work, and really would have been a less elegant approach.

**Comment by brydoyle** [comment]
Was the "HeaterCooler" accessory type considered?
