### ISSUE TITLE
2.0 App

### ISSUE THREAD

**Issue by brydoyle** [karlg100/homebridge-frigidaire#24]
Looks like another upcoming potentially breaking change:

Here’s what to expect:
--
When it’s time to update, you will receive an app notification and email. You will be asked to download our new Frigidaire 2.0 App. Once downloaded, a password reset will be required in the new Frigidaire 2.0 App. Note: When you reset, you can use an existing or new password. After resetting your password, you will be able to enjoy our new app experience.

**Comment by royale56** [comment]
Looks like this took affect for me today and has broken the connection. Would love to get this set back up. Any guidance would be appreciated

**Comment by danielschwartz** [comment]
Having the same issue. There is a slight chance the API itself is the same but the endpoints are different, however given that they required a password reset when transitioning to the new app it makes me feel like there was a true migration which leads me to believe that the API will unfortunately be different. If I have some time over the holiday weekend ill try to get a MITM proxy setup to sniff the traffic from the app but i'm guessing the @karlg100 will have an easier time looking into this since he knows the old authentication scheme and API scheme.

**Comment by Mykbibby** [comment]
Just commenting to ask, most sincerely, that somebody fix this. This was by far my most used Homebridge plugin. I rely on it daily, for everything. This stupid 2.0 Frigidaire upgrade broke the whole thing for me. Anybody who can fix this plugin, or create a new one to replace it, would be my hero.

**Comment by lukeottrey** [comment]
I too am in the same boat. Preparing the house for summer and now the 2.0 update broke the connection. Happy to shout someone a donation for a coffee if they’re able to update the plug-in to work with the wifi AC’s on the new 2.0 platform!

**Comment by amaisano** [comment]
@karlg100 please save us!

**Comment by marekbrz** [comment]
Submitted a pull request which updates the plugin to work with the new API! Nice to have this thing back under HomeKit control...

**Comment by karlg100** [comment]
PR accepted! Thanks @marekbrz!

**Comment by brydoyle** [comment]
@karlg100 - I "frigidaire": "^1.0.5" needs to be updated (to 1.0.6?) in package.json to complete this?

**Comment by attempted** [comment]
@karlg100 please let us know when you publish the updated version to npm.

**Comment by karlg100** [comment]
Published.  Both packages have been upped to 2.0.0.

It would be good to get some feedback before we close this issue.

If a few folks could update via NPM and post back here as to success or issues, would be great!

Karl

**Comment by Maggio695** [comment]
> Published. Both packages have been upped to 2.0.0. It would be good to get some feedback before we close this issue. If a few folks could update via NPM and post back here as to success or issues, would be great! Karl
> […](#)

Can confirm that this is now working for me with the 2.0.0 update. Thanks!

**Comment by lukeottrey** [comment]
To the folks who did this; please let me know where I can send a Starbucks or DD gift card ;)
Appears to be working great; but can someone please confirm that the attached is the best way to have multiple AC’s configured in one house?
This is my HOOBS configuration:
![87FB1E36-1BA3-451F-B0D5-B9BCA96EFFD6](https://user-images.githubusercontent.com/23492815/120325853-12ca0d00-c2b6-11eb-9273-eb5409faebea.jpeg)

**Comment by brydoyle** [comment]
Working now. I have each AC set up as a child bridge (so I don't impact rest of house automation when next issue arises)

**Comment by amaisano** [comment]
I have multiple of these AC units too. What do you mean by “child bridge?”

**Comment by ci1025** [comment]
Just updated and so far so good! Thank you for updating this for 2.0. If there is anywhere we can send donations, please post it here :) Btw: just in case this might help someone else, the serial number in the config didn't work until i removed the first 2 letters, which in my case was "KK"

**Comment by amaisano** [comment]
This isn't 100% working for me. With a single unit, homebridge crashes every 10 minutes or so due to some JSON errors. There are also temperature issues with the unit being set to Celsius which were not present in the 1.0 version.

**Comment by Mykbibby** [comment]
Wow!!!! 

So first of all -- thank you so much to karlg100! You saved the summer.

Second of all -- thank you to ci1025. I couldn't get this to work until I removed the KK from the serial number. Great job figuring that out!

Thanks again!!!!

**Comment by AJRUMORE** [comment]
> This isn't 100% working for me. With a single unit, homebridge crashes every 10 minutes or so due to some JSON errors. There are also temperature issues with the unit being set to Celsius which were not present in the 1.0 version.

I have one AC unit as well and my service is crashing periodically, too. I am using Fahrenheit ￼with no temperature problems, so the crashes are likely independent of the temperature issue.

**Comment by lukeottrey** [comment]
Re: the crashing; same on my end as you AJRUMORE
Here are the errors I have from my "HOOBS" log:
6/7/2021, 7:16:30 AM ERROR: uncaughtException: Unexpected token < in JSON
at position 06/7/2021, 7:16:30 AM SyntaxError: Unexpected token < in JSON
at position 06/7/2021, 7:16:30 AM at JSON.parse (<anonymous>)6/7/2021,
7:16:30 AM at Request._callback
(/hoobs/node_modules/frigidaire/lib/frigidaire.js:236:42)6/7/2021, 7:16:30
AM at Request.self.callback
(/hoobs/node_modules/request/request.js:185:22)6/7/2021,
7:16:30 AM at Request.emit (events.js:315:20)6/7/2021, 7:16:30 AM at
Request.<anonymous> (/hoobs/node_modules/request/request.js:1154:10)6/7/2021,
7:16:30 AM at Request.emit (events.js:315:20)6/7/2021, 7:16:30 AM at
IncomingMessage.<anonymous>
(/hoobs/node_modules/request/request.js:1076:12)6/7/2021,
7:16:30 AM at Object.onceWrapper (events.js:421:28)6/7/2021, 7:16:30 AM at
IncomingMessage.emit (events.js:327:22)6/7/2021, 7:16:30 AM at
endReadableNT (internal/streams/readable.js:1327:12)6/7/2021, 7:16:30 AM at
processTicksAndRejections (internal/process/task_queues.js:80:21)6/7/2021,
7:16:30 AM SyntaxError: Unexpected token < in JSON at position 0 at
JSON.parse (<anonymous>) at Request._callback
(/hoobs/node_modules/frigidaire/lib/frigidaire.js:236:42) at
Request.self.callback (/hoobs/node_modules/request/request.js:185:22) at
Request.emit (events.js:315:20) at Request.<anonymous>
(/hoobs/node_modules/request/request.js:1154:10) at Request.emit
(events.js:315:20) at IncomingMessage.<anonymous>
(/hoobs/node_modules/request/request.js:1076:12) at Object.onceWrapper
(events.js:421:28) at IncomingMessage.emit (events.js:327:22) at
endReadableNT (internal/streams/readable.js:1327:12) at
processTicksAndRejections (internal/process/task_queues.js:80:21)

**Comment by amaisano** [comment]
**Please see linked issues related to crashes**

Here are the two sources of homebridge crash/reboots. One seems to be a problem in the `frigidaire` library, the other, the `homebridge-frigidaire` library. If you have these issues, please post in the relevant issue below to avoid making this a monster thread.

- https://github.com/karlg100/homebridge-frigidaire/issues/28
- https://github.com/karlg100/frigidaire/issues/8

**Comment by karlg100** [comment]
@marekbrz  - going back and reviewing the PR, the platform no longer discovers and auto creates the Accessories in the target account anymore.  Was there a reason you found that it was needed to only allow one device at a time?

in testing with the demo.js in the Frigidaire module, the device listing still works.

**Comment by marekbrz** [comment]
There wasn’t any deliberate reason……the API is slightly different in how devices are handled, and I only had one AC to test against. On my TODO list to fix, though won’t be able to really look at it for another couple of weeks.

**Comment by amaisano** [comment]
@marekbrz could you also confirm/check out [the Celsius problem](https://github.com/karlg100/homebridge-frigidaire/issues/27)?

**Comment by karlg100** [comment]
@amaisano 

> @marekbrz could you also confirm/check out [the Celsius problem](https://github.com/karlg100/homebridge-frigidaire/issues/27)?

open a new issue about this problem.

**Comment by karlg100** [comment]
> There wasn’t any deliberate reason……the API is slightly different in how devices are handled, and I only had one AC to test against. On my TODO list to fix, though won’t be able to really look at it for another couple of weeks.

I've opened a new issue #30 to work on this.  It's going to require restructuring most of the support node module.  Going to close this issue for now with 2.0 working, kind of.

**Comment by karlg100** [comment]
Please open new issues for anything unresolved.

**Comment by amaisan0** [comment]
> @amaisano 
> 
> 
> 
> > @marekbrz could you also confirm/check out [the Celsius problem](https://github.com/karlg100/homebridge-frigidaire/issues/27)?
> 
> 
> 
> open a new issue about this problem.

@karlg100  already had, sorry I hot linked the text to it. Just giving it a bump here since this year has a lot of traction. Thanks for checking in, hope you're well!

**Comment by karlg100** [comment]
All good! Thanks for doing that! I did notice that after the comment and cleaning up open issues on various projects.

Karl
