### ISSUE TITLE
Invalid characteristics for temperature

### ISSUE THREAD

**Issue by amaisano** [karlg100/homebridge-frigidaire#27]
The 2.0 update works! However, now my current temperature numbers are all out of whack (see image). They shouldn't be negative Celsius values... (I use Celsius in the house).

![image](https://user-images.githubusercontent.com/688435/120496853-ebde0a80-c38b-11eb-8591-363a9ad032dd.png)

```
Wed, 02 Jun 2021 16:41:14 GMT frigidaire applianceId 71012357-C83DD4BA1AE2 attribute 0432 has the value 20
Wed, 02 Jun 2021 16:41:14 GMT homebridge-frigidaire getTargetTemperature: 20 -> -6.666666666666666
[6/2/2021, 12:41:14 PM] [homebridge-frigidaire] This plugin generated a warning from the characteristic 'Target Temperature': characteristic was supplied illegal value: number -6.666666666666666 exceeded minimum of 15.5. See https://git.io/JtMGR for more info.
```

**Comment by amaisano** [comment]
If I go into the 2.0 app and change the AC to use Fahrenheit, the UI shows the correct Celsius temps... but shouldn't it show the Fahrenheit temps because that is what the AC and App are set to use? This is really confusing... is this codebase hard-coded for Celsius or is there a config settings I am not using correctly?

**Comment by karlg100** [comment]
HAP and Homebridge handle all temps in C.  I'll look into this as I refactor things.

**Comment by karlg100** [comment]
found the issue. there was a double conversion from F to C happening when in C mode.

fixed and pushed into next release, which will be 2.1.1.
