### ISSUE TITLE
Cannot add my ac to my home bridge setup

### ISSUE THREAD

**Issue by kietiub** [karlg100/homebridge-frigidaire#29]
Installed the plugin and entered my config so not sure where I am going wrong. I have the newer frigidare AC and I am using the new app Frigidaire 2.0 version 1.1.3 and have entered my config text below, 

"platform": "Frigidaire",
		"applianceSerial": "unsure what to enter here so I tried all of these (Serial Number, PNC",
		"username": "my email@gmail.com",
		"password": "my password",
		"deviceId": "O2-w1yjkjewjQt2J_AjaAaeSZZlmTQ501ahP" 

didnt change anything else, did also try changing the device id by a couple of characters, keep getting an error 

ERROR: no appliance found! ensure correct serial number entered in config
no appliance found! ensure correct serial number entered in config
[6/7/2021, 11:35:10 AM] Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:6:13
    at /homebridge/node_modules/homebridge-frigidaire/index.js:46:7
    at /homebridge/node_modules/homebridge-frigidaire/node_modules/frigidaire/lib/frigidaire.js:692:21
    at authStg1GetCallback (/homebridge/node_modules/homebridge-frigidaire/node_modules/frigidaire/lib/frigidaire.js:183:25)
    at getInfoCallback (/homebridge/node_modules/homebridge-frigidaire/node_modules/frigidaire/lib/frigidaire.js:629:22)
    at /homebridge/node_modules/homebridge-frigidaire/node_modules/frigidaire/lib/frigidaire.js:672:14
    at Request._callback (/homebridge/node_modules/homebridge-frigidaire/node_modules/frigidaire/lib/frigidaire.js:278:25)
    at Request.self.callback (/homebridge/node_modules/homebridge-frigidaire/node_modules/request/request.js:185:22)
    at Request.emit (events.js:376:20)
    at Request.<anonymous> (/homebridge/node_modules/homebridge-frigidaire/node_modules/request/request.js:1154:10)

**Comment by kietiub** [comment]
> Installed the plugin and entered my config so not sure where I am going wrong. I have the newer frigidare AC and I am using the new app Frigidaire 2.0 version 1.1.3 and have entered my config text below,
> 
> "platform": "Frigidaire",
> "applianceSerial": "unsure what to enter here so I tried all of these (Serial Number, PNC",
> "username": "my [email@gmail.com](mailto:email@gmail.com)",
> "password": "my password",
> "deviceId": "O2-w1yjkjewjQt2J_AjaAaeSZZlmTQ501ahP"
> 
> didnt change anything else, did also try changing the device id by a couple of characters, keep getting an error
> 
> ERROR: no appliance found! ensure correct serial number entered in config
> no appliance found! ensure correct serial number entered in config
> [6/7/2021, 11:35:10 AM] Error: This callback function has already been called by someone else; it can only be called one time.
> at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:6:13
> at /homebridge/node_modules/homebridge-frigidaire/index.js:46:7
> at /homebridge/node_modules/homebridge-frigidaire/node_modules/frigidaire/lib/frigidaire.js:692:21
> at authStg1GetCallback (/homebridge/node_modules/homebridge-frigidaire/node_modules/frigidaire/lib/frigidaire.js:183:25)
> at getInfoCallback (/homebridge/node_modules/homebridge-frigidaire/node_modules/frigidaire/lib/frigidaire.js:629:22)
> at /homebridge/node_modules/homebridge-frigidaire/node_modules/frigidaire/lib/frigidaire.js:672:14
> at Request._callback (/homebridge/node_modules/homebridge-frigidaire/node_modules/frigidaire/lib/frigidaire.js:278:25)
> at Request.self.callback (/homebridge/node_modules/homebridge-frigidaire/node_modules/request/request.js:185:22)
> at Request.emit (events.js:376:20)
> at Request. (/homebridge/node_modules/homebridge-frigidaire/node_modules/request/request.js:1154:10)

I was reading through the comments from other people and found out that the serial number is from the app, you go into your app and click on your ac and go into support, My serial number started with KK and i was entering that in the config, but you must avoid the first two alphabets and just enter the numbers.

Doing this made it work for me, maybe in the readme you could add avoiding the alphabets for configurations if it helps

**Comment by alfista2600** [comment]
My serial number had a KK in front of it, and it seemed to work when I removed it, but getting other issues now... found yours while looking for help!

**Comment by karlg100** [comment]
I'll add stripping non-numeric chars from the serial number in a future version.
