### ISSUE TITLE
How do yo integrate this with an active Homebridge and a running Frigidaire AC?

### ISSUE THREAD

**Issue by charlestephen** [karlg100/homebridge-frigidaire#3]
Do you have any guidance on actually setting this up with a working AC and Homebridge? I have two of this model AC and homebridge running but no idea how to get this to work.

**Comment by Zyber17** [comment]
(Assuming a working homebridge install)

Run
```sh
git clone https://github.com/karlg100/homebridge-frigidaire
cd homebridge-frigidaire
npm install
```

Then edit homebridge's `config.json` to add
```json
"platforms": [
	{
		"platform": "Frigidaire",
		"name": "Air Conditioner",
		"username": "[your_frigidaire_username]",
		"password": "[your_frigidaire_password]"
	}
]
```

Then run homebridge with the additional `-P /path/to/homebridge-frigidaire/` flag, e.g.
```sh
homebridge -P ./homebridge-frigidaire/
```

**Comment by charlestephen** [comment]
Does this integration still use Frigidaire servers or is it bypassing them altogether?

**Comment by karlg100** [comment]
now published in npm.

**Comment by karlg100** [comment]
use the eve app for fan speed.  note that 100% is auto.  ~91% is full, and so on.
