### ISSUE TITLE
Air Conditioner: Fan Only

### ISSUE THREAD

**Issue by alfista2600** [karlg100/homebridge-frigidaire#34]
Hi all,

Thanks for developing this. I'm only running homebridge to control a Frigidaire Air Conditioner.

It discovered the AC, and offers a target temperature and actual temperature, Cool/Heat/Auto/Off in the 'Accessories' user interface.

Is there something I need to do to be able to toggle to FAN ONLY?

Thanks!

**Comment by brydoyle** [comment]
Set the unit to "heat"

**Comment by alfista2600** [comment]
duh, I should have tried that, lol! Thanks!
