### ISSUE TITLE
Unnamed device crashes homebridge

### ISSUE THREAD

**Issue by andrewtelliott** [karlg100/homebridge-frigidaire#4]
Really just a point for documentation.  If your app on the phone is using a default name, it's actually a null value.  So a user must set their device's name on the frigidaire app (or a change could probably be made to address this programmatically through iteration AC #1, AC #2, etc)

**Comment by karlg100** [comment]
added logic in 1.0.1 to use a default name if one is not specified from the LABEL attribute.  Please test after doing a
`sudo npm update -g homebridge-frigidaire`

**Comment by karlg100** [comment]
verified fixed with my own devices.  only issue that may still be outstanding is if an account has multiple devices, all unnamed.

**Comment by andrewtelliott** [comment]
@karlg100
Great work. I was so thrilled to see this pop up.  Thanks for taking over the project!
