### ISSUE TITLE
Support for dehumidifier

### ISSUE THREAD

**Issue by haywirecoder** [karlg100/homebridge-frigidaire#43]
Hi, 

Have a FGAC5044 dehumidifiers, any plans to add support? Would you accept pull request if I updated the code to support this option? Or should I investigate creating a separate plug-in?

**Comment by tedinorbit** [comment]
I also have a FGAC5044 and would second this request!

**Comment by rrman** [comment]
Yes, would be great to have dehumidifier support!

**Comment by haywirecoder** [comment]
I decide to just take on the activity since I have written a few plug-in prior, it should be release soon. Since I don't have AC units it will only support dehumidifiers units, it will be base on a port of a python code base done by @bm1549. So unfortunately it will share a different implement code base so will not be able to be merge.

**Comment by haywirecoder** [comment]
Completed the plug-in homebridge-frigidaire-dehumidifier with two issues that will be address shortly.

https://github.com/haywirecoder/homebridge-frigidaire-dehumidifier.

**Comment by rrman** [comment]
Great! Thanks. Can't wait to try it soon!
