### ISSUE TITLE
Error 403 : Forbidden

### ISSUE THREAD

**Issue by bwoodruff** [karlg100/homebridge-frigidaire#5]
## The Problem

Homebridge won't run. Homebridge device shows "no response" in HomeKIt. It was working up until installing the frigidaire package and works with it removed.

## Steps taken:

1. Installed homebridge-frigidaire using npm
2. Edited config
3. Restarted homebridge

## config.json

>                 {
>                 "platform": "Frigidaire",
>                 "name": "Frigidaire AC Units",
>                 "username": "myemail@address.example",
>                 "password": "myRealPassword"
>                 }

## /var/log/homebridge.err

> Tue, 04 Sep 2018 23:17:04 GMT frigidaire getting device list, but getting telem first
> Tue, 04 Sep 2018 23:17:04 GMT frigidaire getTelem()
> Tue, 04 Sep 2018 23:17:04 GMT frigidaire 
> Tue, 04 Sep 2018 23:17:04 GMT frigidaire 
> Tue, 04 Sep 2018 23:17:04 GMT frigidaire get()
> Tue, 04 Sep 2018 23:17:04 GMT frigidaire 
> Tue, 04 Sep 2018 23:17:04 GMT frigidaire no sessionId, starting auth sequence
> Tue, 04 Sep 2018 23:17:04 GMT frigidaire authStage1()
> Tue, 04 Sep 2018 23:17:04 GMT frigidaire 
> Tue, 04 Sep 2018 23:17:04 GMT frigidaire 
> Tue, 04 Sep 2018 23:17:04 GMT frigidaire get()
> Tue, 04 Sep 2018 23:17:04 GMT frigidaire 
> Tue, 04 Sep 2018 23:17:04 GMT frigidaire attempts: 0
> Tue, 04 Sep 2018 23:17:04 GMT frigidaire Error 403 : Forbidden
> Tue, 04 Sep 2018 23:17:04 GMT frigidaire stage1 error
> Tue, 04 Sep 2018 23:17:04 GMT frigidaire resetAll()
> Tue, 04 Sep 2018 23:17:04 GMT frigidaire unable to get device list!
> Error: 403 Forbidden
>     at Request._callback (/usr/local/lib/node_modules/homebridge-frigidaire/node_modules/frigidaire/lib/frigidaire.js:267:15)
>     at Request.self.callback (/usr/local/lib/node_modules/homebridge-frigidaire/node_modules/request/request.js:185:22)
>     at emitTwo (events.js:126:13)
>     at Request.emit (events.js:214:7)
>     at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-frigidaire/node_modules/request/request.js:1161:10)
>     at emitOne (events.js:116:13)
>     at Request.emit (events.js:211:7)
>     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-frigidaire/node_modules/request/request.js:1083:12)
>     at Object.onceWrapper (events.js:313:30)
>     at emitNone (events.js:111:20)
>     at IncomingMessage.emit (events.js:208:7)
>     at endReadableNT (_stream_readable.js:1064:12)
>     at _combinedTickCallback (internal/process/next_tick.js:138:11)
>     at process._tickCallback (internal/process/next_tick.js:180:9)

## Other Notes

I have two Frigidaire "Gallery" model window ACs ("Office AC" and "Bedroom AC")
The same credentials do work for the Frigidaire app.
Based on the error message I'd suspect an authentication error, but I've triple checked the credentials, and like I mentioned, they work in the app.

**Comment by bwoodruff** [comment]
The exact model on the units is FGRC0844S1. It looks like there is a newer FGRC0844U1 model available. Maybe this only works with the newer model?

**Comment by brydoyle** [comment]
I have that model working but from version prior to the one published to
NPM.

**Comment by charlestephen** [comment]
@brydoyle What did you change? I have the same error as well.

**Comment by karlg100** [comment]
issue is with the supporting Frigidaire npm module.  They updated the version number to 4.0.2.  New version of that npm package has been updated.   new package has also been published to require the new supporting package version.
{{sudo npm update -g homebridge-frigidaire}}

We may have to come up with a more elegant way to update the app version number if they continue to push new versions frequently.

**Comment by bwoodruff** [comment]
That did the trick. Both ACs now show up in HomeKit. Many thanks.

**Comment by ntableman** [comment]
I am having the same issue now, but it was working for months; trying to update as above but not working. Same 403 issue.

**Comment by ntableman** [comment]
I double checked and I have all the latest versions of the plug in and the libs, any ideas?

Same 403 area.

**Comment by karlg100** [comment]
you'll need to update the version number in the Frigidaire lib.  I'm not running the module right now as it's the offseason for AC.  I'll be able to test an update in a couple months, or just update the version number manually in the other lib.

**Comment by royale56** [comment]
I’ve tried editing the version in the homebridge-frigidaire/node_modules/frigidaire/lib/frigidaire.js 
Without success. Is this the correct file?
