### ISSUE TITLE
Remove temp from homekit

### ISSUE THREAD

**Issue by royale56** [karlg100/homebridge-frigidaire#6]
I find the temp to be inaccurate on my Frigidaire and use a nest for more accurate info. Since I have both hooked up it reports 2 temps in my home app. Is it possible to remove the temp from HomeKit with a “disable” line in the config?

**Comment by karlg100** [comment]
There’s not a way to do this currently.

**Comment by karlg100** [comment]
I've added a disableTemp switch to the home bridge config.  However, the HAP spec requires a CurrentTemperature to be defined.  when it is undefined, it defaults to 32F or 0C.  so it will always read this.  There is no way to disable the temp all together so homekit doesn't receive some value.

**Comment by karlg100** [comment]
added in version 1.0.2.  note dep package Frigidaire@1.0.2 required.
