### ISSUE TITLE
config.pollingInterval is being halved

### ISSUE THREAD

**Issue by eximiusvir** [karlg100/homebridge-frigidaire#9]
In the Homebridge console window, I observed the “[Frigidaire AC Units]” status messages were polling the unit every 5 seconds (based on the timestamps)

The provided default / sample config does not display the config argument “pollingInterval”, which when not provided defaults to 10000 (ms). 

I added pollingInterval (case sensitive) to my platform config and set the value to 30000 (ms) to observe the change in the Homebridge console output and noted the polling interval changed from the observed 5 seconds to 15 seconds. 

I then modified the value to 20000 and observed the pollingInterval became 10 seconds. 

With this in mind, I believe the interval is being halved (/2) somewhere in code.

**Comment by karlg100** [comment]
I wonder if there are two timers being defined somewhere. how many devices do you have?

**Comment by karlg100** [comment]
nope. found the bug.  not even sure why I put that in there. was dividing this.pollInterval by 2.
